name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: |
          sudo -E apt-get update
          sudo install upx
          CGO_ENABLED=0 GOOS=linux go build -o gin_linux -trimpath -ldflags="-s -w"  && upx jfork_linux
          CGO_ENABLED=0 GOOS=darwin go build -o gin_darwin -trimpath -ldflags="-s -w"  && upx jfork_darwin
      - name: pack
        run : |
          ls -al ./artifact/
          rm -rf ./artifact/
          mkdir -p ./artifact
          mv gin_* ./artifact/
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: gin_demo
          path: ./artifact/
      - name: release
        use: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: true
          title: "Auto Build"
          files: ./artifact/*

